[package]
name = "bet_chain"
version = "0.1.0"
edition = "2021"

[dependencies]
rusty-leveldb = "3.0.0"
serde = { version = "1.0.210", features = ["derive"]}
serde_json = "1.0.128"
sha256 = "1.5.0"
tokio = { version = "1.40.0", features = ["full"] }
